### ISSUE TITLE
Install using npm install botisan-ai/sentence-transformers.js

### ISSUE THREAD

**Issue by xnohat** [botisan-ai/sentence-transformers.js#1]
Hi, 
You not release this package on npmpackages so you should update your README.md to
```
npm install botisan-ai/sentence-transformers.js
```
Thanks for must have package

**Comment by gorlikariel** [comment]
@xnohat You just saved me from giving up on the package 😘

**Comment by lhr0909** [comment]
@xnohat Thanks for the interest. We are working on releasing the package in the coming weeks.
